# Generated by Django 5.0.2 on 2025-02-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('logo_2', models.ImageField(upload_to='logo/')),
                ('color', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '1. Header',
            },
        ),
    ]
