# Generated by Django 5.0.2 on 2025-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_image', models.ImageField(upload_to='logo/')),
                ('mobile_image', models.ImageField(upload_to='logo/')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '2. Web Slider',
            },
        ),
    ]
